VIDEOMIDDLEPATH = "/home/sonic/musicProject/middlevideo"
VIDEOOUTPUTPATH = "/home/sonic/workplace/youtubeProject/out"
MERGEVIDEO1PATH = "/home/sonic/workplace/youtubeProject/out/out.mp4"
AUDIOFILE = "/home/sonic/musicProject/originaudio/cale_pinao1.mp3"
AUDIOFILEROOTPATH = "/home/sonic/musicProject/"
PREPAREVIDEOPATH = "/home/sonic/musicProject/originvideo"
TRANSCODEVIDEOPATH = "/home/sonic/musicProject/transcodevideo"
FINALVIDEOPATH = "/home/sonic/musicProject/final/"